### ISSUE TITLE
Unable to read AWS state file

### ISSUE THREAD

**Issue by meltingturret** [fmalk/terraform-plantuml#5]
Great project! I wanted to try on the command line but the output is almost empty - all I get is the AWS Region icon nothing else. Using lastest version of terraform and the AWS provider.

`AWSCloudGroup("aws", "AWS") {
  RegionGroup("us_east_1", "Region us-east-1") {
  }
}`

Tested from mac and ununtu so I guess it is issue processing state file correctly, I have:

`{
  "version": 4,
  "terraform_version": "1.4.5",
  "serial": 3,
}
`
`  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.63.0"
    }
  }
`

**Comment by meltingturret** [comment]
Looks like the issue is, a) IAM role/policy support missing? I would expect for example a role to be linked to a bucket if the permissions incuded bucket name. b) No kinesis support?

**Comment by fmalk** [comment]
Weird that I haven't read your issue before, sorry about that.
If I understand you correctly, you tried the CLI with a file that only declares the providers and region? You gotta declare at least one resource, like a S3 bucket for it to pickup.
If you had policies declared and it didn't show, then that's a bug. And at least for now, no Kinesis support but if you submit a PR with one example of Kinesis declaration, that helps me include it - just create the example with the state file, no need to change any code.

**Comment by fmalk** [comment]
Closing as it looks like an input file issue.
